<a href="https://colab.research.google.com/github/sinhamahi2109/ML_journey/blob/main/gdpDataExtarctionAndProcessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy
!pip install lxml

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.1)

In [6]:
import pandas as pd
import numpy as np
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables=pd.read_html(URL)
df=tables[3]
df.columns=range(df.shape[1])
df=df[[0,2]]
df=df.iloc[1:11,:]
df.columns = ['Country','GDP (Million USD)']
df

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [11]:
df['GDP (Million USD)']=df['GDP (Million USD)'].astype(int)
df['GDP (Million USD)']=df['GDP (Million USD)']/1000
df['GDP (Million USD)']=np.round(df['GDP (Million USD)'],2)
df.rename(columns={'GDP (Million USD)':'GDP (Million USD)'})

           Country  GDP (Million USD)
1    United States               0.03
2            China               0.02
3            Japan               0.00
4          Germany               0.00
5            India               0.00
6   United Kingdom               0.00
7           France               0.00
8            Italy               0.00
9           Canada               0.00
10          Brazil               0.00

In [12]:
df.to_csv('./Largest_economies.csv')